GFAT/Controllers/FoodController.cs
using GFAT.Domain.Extensions;
using GFAT.Domain.ViewModels.Food;
using GFAT.Service.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;


namespace GFAT.Controllers;

public class FoodController : Controller
{
	private readonly IFoodService _foodService;

	public FoodController(IFoodService foodService)
	{
		_foodService = foodService;
	}

	[HttpGet]
	public IActionResult GetFoods()
	{
		var fooder = _foodService.GetFoods();
		if (fooder.StatusCode == Domain.Enum.StatusCode.OK)
		{
			return View(fooder.Data);
		}

		return View("Error", $"{fooder.Description}");
	}

	[Authorize(Roles = "Admin")]
	public async Task<IActionResult> Delete(int id)
	{
		var fooder = await _foodService.DeleteFood(id);
		if (fooder.StatusCode == Domain.Enum.StatusCode.OK)
		{
			return RedirectToAction("GetFoods");
		}

		return View("Error", $"{fooder.Description}");
	}

	public IActionResult Compare() => PartialView();

	[HttpGet]
	public async Task<IActionResult> Save(int id)
	{
		if (id == 0)
			return PartialView();

		var fooder = await _foodService.GetFood(id);
		if (fooder.StatusCode == Domain.Enum.StatusCode.OK)
		{
			return PartialView(fooder.Data);
		}

		ModelState.AddModelError("", fooder.Description);
		return PartialView();
	}

	// string name, string description, decimal price, string CatagoryFood, IFormFile Avatar
	[HttpPost]
	public async Task<IActionResult> Save(FoodViewModel model)
	{
		ModelState.Remove("DateCreate");
		if (ModelState.IsValid)
		{
			if (model.Id == 0)
			{
				byte[] imageData;
				using (var binaryReader = new BinaryReader(model.Avatar.OpenReadStream()))
				{
					imageData = binaryReader.ReadBytes((int)model.Avatar.Length);
				}
				await _foodService.Create(model, imageData);
			}
			else
			{
				await _foodService.Edit(model.Id, model);
			}
			return RedirectToAction("GetFoods");   
		}
		var errorMessage = ModelState.Values
			.SelectMany(v => v.Errors.Select(x => x.ErrorMessage)).ToList().Join();
		return StatusCode(StatusCodes.Status500InternalServerError, new { errorMessage });
	}


	[HttpGet]
	public async Task<ActionResult> GetFood(int id, bool isJson)
	{
		var fooder = await _foodService.GetFood(id);
		if (isJson)
		{
			return Json(fooder.Data);
		}

		return PartialView("GetFood", fooder.Data);
	}

	[HttpPost]
	public async Task<IActionResult> GetFood(string term, int page = 1, int pageSize = 5)
	{
		var fooder = await _foodService.GetFood(term);
		return Json(fooder.Data);
	}

	[HttpPost]
	public JsonResult GetTypes()
	{
		var types = _foodService.GetTypes();
		return Json(types.Data);
	}
}
	

GFAT/Controllers/OrderController.cs
using GFAT.Domain.ViewModels.Order;
using GFAT.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace GFAT.Controllers;

public class OrderController : Controller
{
    // GET
    private readonly IOrderService _orderService;

    public OrderController(IOrderService orderService)
    {
        _orderService = orderService;
    }

    [HttpGet]
    public IActionResult CreateOrder(long id)
    {
        var orderModel = new CreateOrderViewModel()
        {
            FoodId = id,
            Login = User.Identity.Name,
            Quantity = 0
        };
        return View(orderModel);
    }
        
    [HttpPost]
    public async Task<IActionResult> CreateOrder(CreateOrderViewModel model)
    {
        if (ModelState.IsValid)
        {
            var response = await _orderService.Create(model);
            if (response.StatusCode == Domain.Enum.StatusCode.OK)
            {
                return Json(new { description = response.Description });
            }
        }
        return StatusCode(StatusCodes.Status500InternalServerError);
    }
        
    public async Task<IActionResult> Delete(int id)
    {
        var response = await _orderService.Delete(id);
        if (response.StatusCode == Domain.Enum.StatusCode.OK)
        {
            return RedirectToAction("Detail", "Basket");
        }
        return View("Error", $"{response.Description}");
    }

}

GFAT/Views/Food/Compare.cshtml
<div class="row">
    <div class="col">
        <select class="form-control" id="firstCarId"></select>
    </div>
    <div class="col">
        <select class="form-control" id="secondCarId"></select>
    </div>
</div>

<div style="padding: 10px;"></div>

<div class="row">
    <div class="col-md-6">
        <div class="card-body">
            <h5 class="card-title" id="firstCardTitleId"></h5>
            <p class="card-text" id="firstCardDescId"></p>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item" id="firstCardSpeedId"></li>
            <li class="list-group-item" id="firstCardPriceId"></li>
            <li class="list-group-item" id="firstCardModelId"></li>
            <li class="list-group-item" id="firstCardDateCreateId"></li>
        </ul>
    </div>
    <div class="col-md-6">
       <div class="card-body">
           <h5 class="card-title" id="secondCardTitleId"></h5>
           <p class="card-text" id="secondCardDescId"></p>
       </div>
       <ul class="list-group list-group-flush">
           <li class="list-group-item" id="secondCardSpeedId"></li>
           <li class="list-group-item" id="secondCardPriceId"></li>
           <li class="list-group-item" id="secondCardModelId"></li>
           <li class="list-group-item" id="secondCardDateCreateId"></li>
       </ul> 
    </div>
</div>

<div style="padding: 10px;"></div>

<div class="text-white bg-secondary" id="warningCardId">
    <div class="bg-secondary card-header text-white">
        Предупреждение
    </div>
    <div class="card-body">
        <blockquote class="blockquote mb-0">
            <p id="warningId"></p>
        </blockquote>
    </div>
</div>

<div style="padding: 10px;"></div>

<div id="resultCardId">
  <div class="bg-secondary card-header text-white">
    Результат
  </div>
  <div class="card-body">
    <ul class="list-group list-group-flush">
        <li class="list-group-item" id="resultSpeedId"></li>
        <li class="list-group-item" id="resultPriceId"></li>
    </ul>
  </div>
</div>

<script src="~/lib/select2/js/select2.full.min.js"></script>
<script> 
$(document).ready(function () {
    
    $('#firstCardId').hide();
    $('#secondCardId').hide();
    $('#warningCardId').hide();
    $('#resultCardId').hide();
    
    let firstCar = null; 
    let secondCar = null;        
    
    $('#firstCarId, #secondCarId').select2({
       placeholder: "Выберите машину",
       minimumInputLength: 2,
       allowClear: true,
       ajax: {
            type: "POST",
            url: "@Url.Action("GetFood", "Food")",
            dataType: "json",
            data: function (params) { 
                var query = {
                    term: params.term,
                    page: params.page || 1,
                    pageSize: params.pageSize || 5
                };
                return query;
            },
            processResults: function (result) {
                return {
                    results: $.map(result, function (val, index) {
                        return {
                            id: index, 
                            text: val
                        };
                    }),
                };
            }
        }
    });      

    function fillData(val, cardId){
        if (cardId === 'firstCardId'){
            $('#firstCardId').show();
            $('#firstCardTitleId')[0].innerText = 'Название: ' + val.name;
            $('#firstCardDescId')[0].innerText = 'Описание: ' + val.description;
            $('#firstCardSpeedId')[0].innerText = 'Скорость: ' + val.speed + ' км/ч';
            $('#firstCardPriceId')[0].innerText = 'Стоимость: ' + val.price + ' ₽';
            $('#firstCardModelId')[0].innerText = 'Модель: ' + val.model;
            $('#firstCardDateCreateId')[0].innerText = 'Дата создания: ' + val.dateCreate;
        } else {
            $('#secondCarId').show();
            $('#secondCardTitleId')[0].innerText = 'Название: ' + val.name;
            $('#secondCardDescId')[0].innerText = 'Описание: ' + val.description;
            $('#secondCardSpeedId')[0].innerText = 'Скорость: ' + val.speed + ' км/ч';
            $('#secondCardPriceId')[0].innerText = 'Стоимость: ' + val.price + ' ₽';
            $('#secondCardModelId')[0].innerText = 'Модель: ' + val.model;
            $('#secondCardDateCreateId')[0].innerText = 'Дата создания: ' + val.dateCreate;
        }
        compareCars();
    }
   
    
    $("#secondCarId").on("change", function(){
        const id = this.value;
        if (id === "") return;
        $.get("/Car/GetCar", { id : id, isJson : true }, function(data) {
            secondCar = data;
            fillData(secondCar, "secondCarId");
        });
    });
    
    $("#firstCarId").on("change", function(){
        const id = this.value;
        if (id === "") return;
        $.get("/Car/GetCar", { id : id, isJson : true }, function(data) {
            firstCar = data;
            fillData(firstCar, "firstCardId");
        });            
    });
    
    function compareCars(){
        if (firstCar === null) {
            $('#warningId')[0].innerText = 'Вы не выбрали первый автомобиль';
            $('#warningCardId').show();
            return;
        }
        
        if (secondCar === null) {
            $('#warningId')[0].innerText = 'Вы не выбрали второй автомобиль';
            $('#warningCardId').show();
            return;
        }    
        
        var speed = $('#resultSpeedId')[0];
        if (firstCar.speed > secondCar.speed) {
            speed.innerText = 'Скорость ' + firstCar.name + ' выше, чем у ' + secondCar.name;
        } else if (firstCar.speed === secondCar.speed) {
            speed.innerText = 'Скорость ' + secondCar.name + ' и ' + firstCar.name + ' равны';
        } else {
            speed.innerText = 'Скорость ' + secondCar.name + ' выше, чем у ' + firstCar.name;
        }
        
        var price = $('#resultPriceId')[0];
        if (firstCar.price > secondCar.price) {
            price.innerText = 'Стоимость ' + firstCar.name + ' выше, чем у ' + secondCar.name;
        } else if (firstCar.price === secondCar.price) {
            price.innerText = 'Стоимость ' + firstCar.name + ' и ' + secondCar.name + ' равны';
        } else {
           price.innerText = 'Стоимость ' + firstCar.name + ' выше, чем у ' + secondCar.name;
        }

        $('#resultCardId').show();
        $('#warningCardId').hide();
    }
  });
</script>

GFAT/Views/Food/GetFood.cshtml
@model GFAT.Domain.ViewModels.Food.FoodViewModel

@*data:image/jpeg;base64,@Convert.ToBase64String(Model?.Image ?? Array.Empty<byte>())*@
<form>
    <div class="row">
        <div class="col-md-12">
            <img src="https://images.wallpaperscraft.ru/image/single/zdaniia_ogni_svechenie_279703_300x168.jpg"
                 class="img-fluid rounded-start rounded" alt="@Model?.Name">
        </div>
    </div>
    <div class="row">
        <div class="form-group col-md-4">
            <label asp-for="@Model.Name" class="col-form-label"></label>
            <input type="text" class="form-control" asp-for="@Model.Name">
        </div>
     
        <div class="form-group col-md-4">
            <label asp-for="@Model.Price" class="col-form-label"></label>
            <input type="text" class="form-control" asp-for="@Model.Price" />
        </div>
    </div>
    <div class="row">
        <div class="form-group col-md-12">
            <label asp-for="@Model.Description" class="col-form-label"></label>
            <textarea type="text" class="form-control" asp-for="@Model.Description"></textarea>
        </div>
    </div>
    <div class="row">
        <div class="form-group col-md-6">
            <label asp-for="@Model.CatagoryFood" class="col-form-label"></label>
            <select class="form-control" id="carTypeId2">
                <option value="@Model.CatagoryFood">@Model.CatagoryFood</option>
            </select>
        </div>
    </div>
</form>

<style>
    label {
        color: black;
    }
</style>

<script src="~/lib/select2/js/select2.full.min.js"></script>
<script>
$('#carTypeId2').select2({
   placeholder: "Выберите тип",
   minimumInputLength: 0,
   allowClear: true,
   ajax: {
        type: "POST",
        url: "@Url.Action("GetTypes", "Food")",
        dataType: "json",
        processResults: function (result) {
            return {
                results: $.map(result, function (val, index) {
                    return {
                        id: index, 
                        text: val
                    };
                }),
            };
        }
    }
});
</script>

GFAT/Views/Food/GetFoods.cshtml
@using GFAT.Domain.ViewModels.Food
@model List<GFAT.Domain.Models.Food>


@{
    ViewBag.Title = "Список автомобилей";
    Layout = "_Layout";
}

@{
    var cardStyle = "col-md-12";
    if (Model != null)
    {
        switch (Model.Count)
        {
            case 2:
                cardStyle = "col-md-6";
                break;
            case 3:
                cardStyle = "col-md-4";
                break;
        }
    }
}

<style>
    .card-buttons-group {
        text-align: right;
        padding: 10px;
    }
</style>

<div class="card col-md-12" style="margin: 10px;">
    <div class="card-buttons-group">
        <button class='btn btn-primary' id='compareBtnId'>Сравнение</button>
        @if (User.IsInRole("Admin"))
        {
            <button class='btn btn-success' id='addCarId'>Добавить</button>   
        }
    </div>
</div>

<div style="padding: 10px;"></div>
@if (Model == null)
{
    <div class="card col-md-12">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="https://images.wallpaperscraft.ru/image/single/bmw_fary_podsvetka_137326_1280x720.jpg" 
                     class="img-fluid rounded-start rounded">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title text-center">Список машин пуст :(</h5>
                    <p class="card-text">
                        Список пополниться позже, не расстраивайтесь
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div style="padding: 10px;"></div>
    <div class="card text-center">
        <div class="card-header">
            <ul class="nav nav-pills card-header-pills">
                <li class="nav-item">
                    <a class="nav-link active" href="#">Active</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                </li>
            </ul>
        </div>
        <div class="card-body">
            <h5 class="card-title">Special title treatment</h5>
            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
    </div>
}
else
{
    <div class="row">
        @foreach (var car in Model)
        {
            <div class="row row-cols-1 @cardStyle text-center">
                <div class="col" style="padding: 10px;">
                    <div class="card">
                        <img src="~/img/Mustang.jpg" class="card-img-top card-image" alt="@car.name">
                        <div class="card-body">
                            <h5 class="card-title">Название: @car.name</h5>
                            <p class="card-text">Краткое описание: @car.description.Substring(0, 40) ...</p>
                        </div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">Стоимость: @car.price </li>
                        </ul>
                        <div class="card-body">
                            <button class="btn btn-primary" onclick="openModal({ url: '/Car/GetCar', data: '@car.id' })"
                                    data-toggle="ajax-modal" data-target="Modal">Открыть</button>
                             @if (User.IsInRole("Admin"))
                             {
                                 <a asp-controller="Food" asp-action="Delete" asp-route-id="@car.id" class="btn btn-danger">Удалить</a>
                             }
                             <a asp-controller="Order" asp-action="CreateOrder" asp-route-id="@car.id" class="btn btn-success">В корзину</a>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>   
}

@section pageScripts {

    <script src="~/js/modal.js"></script>
    <script>
       let modal = $('#modal'); 

       $('#saveBtn').on('click', function () {
           $.ajax({
               url: '@Url.Action("Save")',
               type: 'POST',
               // data: JSON.stringify(model),
               success: function (response) {
                   Swal.fire({
                       title: 'Информация',
                       text: response.description,
                       icon: 'success',
                       confirmButtonText: 'Окей'
                   })
               },
               error: function (data) {
                   Swal.fire({
                       title: 'Информация',
                       text: 'Ошибка валидации',
                       icon: 'error',
                       confirmButtonText: 'Окей'
                   })
               }
           }) 
        });
        
       $('#compareBtnId').on('click', function (){
           $.ajax({
               type: 'GET',
               url : '@Url.Action("Compare")',
               success: function (response) {
                   $('.modal-dialog').addClass("modal-lg");
                   modal.find(".modal-body").html(response);
                   modal.modal('show')
               }
           });
       });
        
       $(".btn-close").click(function(){
            modal.modal('hide');
       });
       
       $('#addCarId').on('click', function () {
           $.ajax({
              type: 'GET',
              url : '/Car/Save',
              success: function (response) {
                  $('.modal-dialog').removeClass("modal-lg");
                  modal.find(".modal-body").html(response);
                  modal.modal('show')
              },
              failure: function () {
                modal.modal('hide')
              },
              error: function (response) {
                  alert(response.responseText);
              }
          });
       });
       
    </script>
}

GFAT/Views/Food/Save.cshtml
@model GFAT.Domain.ViewModels.Food.FoodViewModel

@{
    var textTitle = Model?.Id == 0 ? "Изменение данных" : "Добавление данных";
}

<form asp-controller="Food" asp-action="Save" enctype="multipart/form-data" id="formSaveCar">
    <input asp-for="Id" hidden />
    <div asp-validation-summary="All" style="font-size:23px; font-family:Impact, serif" class="text-danger text-center"></div>
    <div class="row">
        <div class="form-group col-md-4">
            <label asp-for="@Model.Name" class="col-form-label"></label>
            <input type="text" class="form-control" asp-for="@Model.Name">
        </div>
        <div class="form-group col-md-4">
            <label asp-for="@Model.Price" class="col-form-label"></label>
            <input type="text" class="form-control" asp-for="@Model.Price" />
        </div>
    </div>
    <div class="row">
        <div class="form-group col-md-12">
            <label asp-for="@Model.Description" class="col-form-label"></label>
            <textarea type="text" class="form-control" asp-for="@Model.Description"></textarea>
        </div>
    </div>
    <div class="row">
        <div class="form-group col-md-6">
            <label asp-for="@Model.CatagoryFood" class="col-form-label"></label>
            <select asp-for="@Model.CatagoryFood" class="form-control" id="carTypeId"></select>
        </div>
        <div class="form-group col-md-6">
            <label class="col-form-label">Изображение</label>
            <input asp-for="@Model.Avatar" class="form-control" type="file">
        </div>
    </div>
</form>

<script src="~/lib/select2/js/select2.full.min.js"></script>
<script>
   $('#carTypeId').select2({
      placeholder: "Выберите тип",
      minimumInputLength: 0,
      allowClear: true,
      ajax: {
           type: "POST",
           url: "@Url.Action("GetTypes", "Food")",
           dataType: "json",
           processResults: function (result) {
               return {
                   results: $.map(result, function (val, index) {
                       return {
                           id: index, 
                           text: val
                       };
                   }),
               };
           }
       }
   });
</script>

<style>
    label {
        color: black;
    }
</style>